name: Build Static PHP 8.3 on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout PHP Source Code
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: PHP-8.3
          submodules: recursive

      - name: Install Dependencies
        run: |
          choco install -y nasm strawberryperl winflexbison ninja cmake
          echo "Installed build dependencies."

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install libxml2 openssl curl sqlite3
          echo "VCPKG_PATH=C:\vcpkg" >> $GITHUB_ENV

            - name: Configure PHP Build
              shell: cmd
              run: |
                cd php-src
                buildconf
                configure --enable-static --disable-shared --disable-cli --enable-embed=static ^
                --with-openssl --with-libxml --with-curl --enable-mbstring ^
                --enable-bcmath --enable-intl --enable-pdo --with-mysqli ^
                --enable-apcu=static --enable-redis=static --enable-ffi=static
                echo "PHP configuration done."

      - name: Compile PHP
        run: |
          cd php-src
          nmake
          echo "PHP build completed."

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-static-build
          path: php-src\x64\Release\
