name: Build Static PHP 8.3 on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout PHP Source Code
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: PHP-8.3
          submodules: recursive
          fetch-depth: 1

      - name: Debug Directory Structure
        run: dir
        shell: cmd

      - name: Verify php-src Directory Exists
        run: |
          if exist php-src (
            echo "php-src exists"
          ) else (
            echo "Error: php-src directory missing!"
            exit 1
          )
        shell: cmd

      - name: Configure PHP Build
        shell: cmd
        run: |
          cd php-src
          buildconf
          configure --enable-static --disable-shared --disable-cli --enable-embed=static ^
          --with-openssl --with-libxml --with-curl --enable-mbstring ^
          --enable-bcmath --enable-intl --enable-pdo --with-mysqli ^
          --enable-apcu=static --enable-redis=static --enable-ffi=static
          echo "PHP configuration done."
