name: Build Static PHP 8.3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y \
            autoconf bison build-essential curl libxml2-dev \
            libsqlite3-dev libonig-dev libzip-dev libjpeg-dev \
            libpng-dev libfreetype6-dev libssl-dev libcurl4-openssl-dev \
            libicu-dev libpq-dev libreadline-dev libxslt1-dev \
            libmagickwand-dev imagemagick libbz2-dev libdb-dev libsodium-dev \
            libgd-dev

      - name: Download PHP 8.3 Source
        run: |
          wget https://www.php.net/distributions/php-8.3.0.tar.gz
          tar -xvzf php-8.3.0.tar.gz
          cd php-8.3.0

      - name: Configure PHP for Static Build
        run: |
          cd php-8.3.0
          ./configure --prefix=$GITHUB_WORKSPACE/php-8.3-static \
            --enable-static=yes --enable-shared=no \
            --enable-bcmath --enable-calendar --enable-mbstring \
            --enable-exif --enable-intl --enable-opcache \
            --enable-pcntl --enable-phar --enable-posix \
            --enable-sockets --enable-tokenizer --enable-zip \
            --with-curl --with-dom --with-fileinfo --with-gd \
            --with-iconv --with-mysqli --with-pdo-mysql \
            --with-pdo-pgsql --with-pdo-sqlite --with-pgsql \
            --with-readline --with-sodium --with-xmlrpc \
            --with-xml --with-xsl --with-zlib \
            --with-openssl --with-imagick

      - name: Build PHP 8.3
        run: |
          cd php-8.3.0
          make -j$(nproc)
          make install

      - name: Verify PHP Build
        run: |
          ./php-8.3-static/bin/php -v
          ./php-8.3-static/bin/php -m

      - name: Upload PHP Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-php-8.3
          path: php-8.3-static/bin/php
